name: Publish on Modrinth & CurseForge

on:
  release:
    types: [ published ]

env:
  CURSEFORGE_ID: 851574
  MODRINTH_ID: fYYSAh4R
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ env.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: '[NeoForge] v${{github.ref_name}}'
          version-type: beta
          files: neoforge/build/libs/!(*-@(shadow|dev|sources|javadoc|all)).jar

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ env.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: '[Fabric] v${{github.ref_name}}'
          version-type: beta
          files: fabric/build/libs/!(*-@(shadow|dev|sources|javadoc|all)).jar
